source "https://rubygems.org"

ruby "3.3.0"

# Rails API-only
gem "rails", "~> 7.1.0"

# PostgreSQL adapter
gem "pg", "~> 1.5"

# Application server
gem "puma", "~> 6.4"

# JSON serialization
gem "oj", "~> 3.16"

# Timezone data
gem "tzinfo-data", platforms: %i[windows jruby]

# Reduces boot times through caching
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
