# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x0e\n\x0cHelloRequest\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x12\n\x10GetOrdersRequest\",\n\x0eGetOrdersReply\x12\x1a\n\x06orders\x18\x01 \x03(\x0b\x32\n.api.Order\"a\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x05\x12\x13\n\x0btotal_cents\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t2u\n\nApiService\x12.\n\x08SayHello\x12\x11.api.HelloRequest\x1a\x0f.api.HelloReply\x12\x37\n\tGetOrders\x12\x15.api.GetOrdersRequest\x1a\x13.api.GetOrdersReplyB\x06\xaa\x02\x03\x41pib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\003Api'
  _globals['_HELLOREQUEST']._serialized_start=18
  _globals['_HELLOREQUEST']._serialized_end=32
  _globals['_HELLOREPLY']._serialized_start=34
  _globals['_HELLOREPLY']._serialized_end=63
  _globals['_GETORDERSREQUEST']._serialized_start=65
  _globals['_GETORDERSREQUEST']._serialized_end=83
  _globals['_GETORDERSREPLY']._serialized_start=85
  _globals['_GETORDERSREPLY']._serialized_end=129
  _globals['_ORDER']._serialized_start=131
  _globals['_ORDER']._serialized_end=228
  _globals['_APISERVICE']._serialized_start=230
  _globals['_APISERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
