worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    access_log off;

    resolver 127.0.0.11 valid=5s;

    lua_package_path "/usr/local/openresty/lualib/?.lua;;";

    # Connection pool for postgres (shared per worker)
    lua_shared_dict pg_pool 1m;

    init_by_lua_block {
        require("app")
    }

    server {
        listen 8000;

        location = / {
            default_type application/json;
            content_by_lua_block {
                require("app").hello()
            }
        }

        location = /orders {
            default_type application/json;
            content_by_lua_block {
                require("app").orders()
            }
        }
    }
}
